ADR-45 - Testing flow for long-running server tests
nats-io/nats-architecture-and-design pull request #305
Opened 2024-09-16 22:00 UTC by mprimi

2024-09-16 22:15 UTC, wallyqs commented on adr/ADR-45.md
> + - Create a new test for long files in the server package, e.g.: `server/long_running_tests.go`
```suggestion
 - Create a new test for long files in the server package, e.g.: `server/long_running_test.go`
```

2024-09-17 00:01 UTC, ReubenMathew requested changes

2024-09-17 00:01 UTC, ReubenMathew commented on adr/ADR-45.md
> +The list of currently skipped test is relatively short:
```suggestion
The list of currently skipped tests is relatively short:
```

2024-09-17 06:38 UTC, ripienaar commented
I think it's a useful approach and worth doing but not sure it merits an ADR - we tend to use these for big design things not for decisions

2024-09-17 11:18 UTC, scottf commented
I'd like to see a test design doc instead of references to code, and I think that does belong here. I might remove the server category to keep it distinct as testing.

2024-09-17 16:24 UTC, mprimi commented
> not sure it merits an ADR

Fair enough. I won't try to merge this PR. 
I wanted to collect some feedback/opinions, then I'll close it.

2024-09-24 20:58 UTC, mprimi commented
GH Pipeline: https://github.com/nats-io/nats-server/actions/workflows/long-tests.yaml
BK Pipeline: https://buildkite.com/synadia/nats-server-long-running-tests
BK Analytics: https://buildkite.com/organizations/synadia/analytics/suites/nats-server-long-running-tests
PR: https://github.com/nats-io/nats-server/pull/5920

2024-09-24 20:58 UTC, closed without merging